<article>
	<h1><span>Radiam Configuration</span></h1>

	<ul class="nav">
		<li><a href="#settings">Radiam Settings</a></li>
		<li><a href="#projects">Projects</a></li>
	</ul>

	<section id="settings">
		<h2><span>Global Settings</span></h2>
		<p>You can add or edit global settings for the Radiam component.</p>
		<dl>
			<dt>configname: radiam_host_url</dt>
			<dd>This is the full URL to where Radiam is.  It should use https and be in this format:<br/>
			https://radiam.somewhere.edu/<br/>
			If it is running on a non-standard port, then include the port:<br/>
			https://radiam.somwehere.edu:8100/</dd>
		</dl>
	</section>

	<section id="projects">
		<h2><span>Projects</span></h2>

		<p>Here you associate HubZero projects with Radiam projects.</p>

		<dl>
			<dt>HubZero Project</dt>
			<dd>Select the HubZero project.  It must already exist.</dd>

			<dt>Radiam Project UUID</dt>
			<dd>Enter the UUID for the Radiam project</dd>

			<dt>Radiam Project UUID</dt>
			<dd>Enter the UUID for the Radiam project</dd>

			<dt>Radiam User UUID</dt>
			<dd>Enter the UUID for the Radiam user</dd>

			<dt>Radiam User Token</dt>
			<dd>Enter a valid token for the Radiam user</dd>

		</dl>
	</section>
</article>
