<article>
	<h1><span>Radiam Configuration</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#global">Global Settings</a></li>
		<li><a href="#projects">Projects</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>This is the Radiam administrative configuration.</p>
	</section>
	<section id="global">
		<h2><span>Global Settings</span></h2>
		<p>You can add or edit global settings for the Radiam component.</p>
		<p>:</p>
		<dl>
			<dt>configname: radiam_api_url</dt>
			<dd>This is the full URL to where the Radiam API is.  It should be in this format:<br/>
			https://radiam.somewhere.edu/api/</dd>
		</dl>
	</section>
	<section id="projects">
		<h2><span>Projects</span></h2>

		<p>Here you associate HubZero projects with Radiam projects.</p>

		<dl>
			<dt>HubZero Project</dt>
			<dd>Select the HubZero project.  It must already exist.</dd>

			<dt>Radiam Project UUID</dt>
			<dd>Enter the UUID for the Radiam project</dd>

			<dt>Radiam Project UUID</dt>
			<dd>Enter the UUID for the Radiam project</dd>

			<dt>Radiam User UUID</dt>
			<dd>Enter the UUID for the Radiam user</dd>

			<dt>Radiam User Token</dt>
			<dd>Enter a valid token for the Radiam user</dd>

		</dl>
	</section>
</article>